// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PermintaanData.Data;

#nullable disable

namespace PermintaanData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260405181346_FixSeedDataConflicts")]
    partial class FixSeedDataConflicts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PermintaanData.Models.AppUser", b =>
                {
                    b.Property<int>("AppUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("AppUserID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppUserID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NamaLengkap");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Username");

                    b.HasKey("AppUserID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUser", "public");
                });

            modelBuilder.Entity("PermintaanData.Models.AuditLogPPID", b =>
                {
                    b.Property<Guid>("AuditLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AuditLogID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Keterangan")
                        .HasColumnType("text")
                        .HasColumnName("Keterangan");

                    b.Property<string>("Operator")
                        .HasColumnType("text")
                        .HasColumnName("Operator");

                    b.Property<Guid>("PermohonanPPIDID")
                        .HasColumnType("uuid")
                        .HasColumnName("PermohonanPPIDID");

                    b.Property<int?>("StatusBaru")
                        .HasColumnType("integer")
                        .HasColumnName("StatusBaru");

                    b.Property<int?>("StatusLama")
                        .HasColumnType("integer")
                        .HasColumnName("StatusLama");

                    b.HasKey("AuditLogID");

                    b.HasIndex("PermohonanPPIDID");

                    b.ToTable("AuditLogPPID", "public");
                });

            modelBuilder.Entity("PermintaanData.Models.DokumenPPID", b =>
                {
                    b.Property<Guid>("DokumenPPIDID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("DokumenPPIDID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int?>("JenisDokumenPPIDID")
                        .HasColumnType("integer")
                        .HasColumnName("JenisDokumenPPIDID");

                    b.Property<string>("NamaDokumenPPID")
                        .HasColumnType("text")
                        .HasColumnName("NamaDokumenPPID");

                    b.Property<string>("NamaJenisDokumenPPID")
                        .HasColumnType("text")
                        .HasColumnName("NamaJenisDokumenPPID");

                    b.Property<Guid?>("PermohonanPPIDID")
                        .HasColumnType("uuid")
                        .HasColumnName("PermohonanPPIDID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UploadDokumenPPID")
                        .HasColumnType("text")
                        .HasColumnName("UploadDokumenPPID");

                    b.HasKey("DokumenPPIDID");

                    b.HasIndex("JenisDokumenPPIDID");

                    b.HasIndex("PermohonanPPIDID");

                    b.ToTable("DokumenPPID", "public");
                });

            modelBuilder.Entity("PermintaanData.Models.JadwalPPID", b =>
                {
                    b.Property<Guid>("JadwalPPIDID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("JadwalPPIDID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("JenisJadwal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("JenisJadwal");

                    b.Property<string>("NamaPIC")
                        .HasColumnType("text")
                        .HasColumnName("NamaPIC");

                    b.Property<Guid?>("PermohonanPPIDID")
                        .HasColumnType("uuid")
                        .HasColumnName("PermohonanPPIDID");

                    b.Property<DateOnly?>("Tanggal")
                        .HasColumnType("date")
                        .HasColumnName("Tanggal");

                    b.Property<string>("TeleponPIC")
                        .HasColumnType("text")
                        .HasColumnName("TeleponPIC");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<TimeOnly?>("Waktu")
                        .HasColumnType("time without time zone")
                        .HasColumnName("Waktu");

                    b.HasKey("JadwalPPIDID");

                    b.HasIndex("PermohonanPPIDID");

                    b.ToTable("JadwalPPID", "public");
                });

            modelBuilder.Entity("PermintaanData.Models.JenisDokumenPPID", b =>
                {
                    b.Property<int>("JenisDokumenPPIDID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("JenisDokumenPPIDID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JenisDokumenPPIDID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<string>("NamaJenisDokumenPPID")
                        .HasColumnType("text")
                        .HasColumnName("NamaJenisDokumenPPID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("JenisDokumenPPIDID");

                    b.ToTable("JenisDokumenPPID", "public");

                    b.HasData(
                        new
                        {
                            JenisDokumenPPIDID = 1,
                            IsActive = true,
                            NamaJenisDokumenPPID = "KTP"
                        },
                        new
                        {
                            JenisDokumenPPIDID = 2,
                            IsActive = true,
                            NamaJenisDokumenPPID = "Surat Permohonan"
                        },
                        new
                        {
                            JenisDokumenPPIDID = 3,
                            IsActive = true,
                            NamaJenisDokumenPPID = "Proposal Penelitian"
                        },
                        new
                        {
                            JenisDokumenPPIDID = 4,
                            IsActive = true,
                            NamaJenisDokumenPPID = "Akta Notaris"
                        },
                        new
                        {
                            JenisDokumenPPIDID = 5,
                            IsActive = true,
                            NamaJenisDokumenPPID = "Dokumen Identifikasi (TTD)"
                        },
                        new
                        {
                            JenisDokumenPPIDID = 6,
                            IsActive = true,
                            NamaJenisDokumenPPID = "Surat Izin"
                        },
                        new
                        {
                            JenisDokumenPPIDID = 7,
                            IsActive = true,
                            NamaJenisDokumenPPID = "Data Hasil"
                        });
                });

            modelBuilder.Entity("PermintaanData.Models.Keperluan", b =>
                {
                    b.Property<int>("KeperluanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("KeperluanID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KeperluanID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("NamaKeperluan")
                        .HasColumnType("text")
                        .HasColumnName("NamaKeperluan");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("KeperluanID");

                    b.ToTable("Keperluan", "public");

                    b.HasData(
                        new
                        {
                            KeperluanID = 1,
                            NamaKeperluan = "Observasi"
                        },
                        new
                        {
                            KeperluanID = 2,
                            NamaKeperluan = "Permintaan Data"
                        },
                        new
                        {
                            KeperluanID = 3,
                            NamaKeperluan = "Wawancara"
                        });
                });

            modelBuilder.Entity("PermintaanData.Models.PermohonanPPID", b =>
                {
                    b.Property<Guid>("PermohonanPPIDID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PermohonanPPIDID");

                    b.Property<DateOnly?>("BatasWaktu")
                        .HasColumnType("date")
                        .HasColumnName("BatasWaktu");

                    b.Property<Guid?>("BidangID")
                        .HasColumnType("uuid")
                        .HasColumnName("BidangID");

                    b.Property<DateTime?>("CratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CratedAt");

                    b.Property<bool>("IsObservasi")
                        .HasColumnType("boolean")
                        .HasColumnName("IsObservasi");

                    b.Property<bool>("IsPermintaanData")
                        .HasColumnType("boolean")
                        .HasColumnName("IsPermintaanData");

                    b.Property<bool>("IsWawancara")
                        .HasColumnType("boolean")
                        .HasColumnName("IsWawancara");

                    b.Property<string>("JudulPenelitian")
                        .HasColumnType("text")
                        .HasColumnName("JudulPenelitian");

                    b.Property<string>("KategoriPemohon")
                        .HasColumnType("text")
                        .HasColumnName("KategoriPemohon");

                    b.Property<string>("LatarBelakang")
                        .HasColumnType("text")
                        .HasColumnName("LatarBelakang");

                    b.Property<string>("LoketJenis")
                        .HasColumnType("text")
                        .HasColumnName("LoketJenis");

                    b.Property<string>("NamaBidang")
                        .HasColumnType("text")
                        .HasColumnName("NamaBidang");

                    b.Property<string>("NamaProdusenData")
                        .HasColumnType("text")
                        .HasColumnName("NamaProdusenData");

                    b.Property<string>("NoPermohonan")
                        .HasColumnType("text")
                        .HasColumnName("NoPermohonan");

                    b.Property<string>("NoSuratPermohonan")
                        .HasColumnType("text")
                        .HasColumnName("NoSuratPermohonan");

                    b.Property<string>("Pengampu")
                        .HasColumnType("text")
                        .HasColumnName("Pengampu");

                    b.Property<Guid?>("PribadiID")
                        .HasColumnType("uuid")
                        .HasColumnName("PribadiID");

                    b.Property<int?>("Sequance")
                        .HasColumnType("integer")
                        .HasColumnName("Sequance");

                    b.Property<int?>("StatusPPIDID")
                        .HasColumnType("integer")
                        .HasColumnName("StatusPPIDID");

                    b.Property<DateOnly?>("TanggalPermohonan")
                        .HasColumnType("date")
                        .HasColumnName("TanggalPermohonan");

                    b.Property<DateOnly?>("TanggalSelesai")
                        .HasColumnType("date")
                        .HasColumnName("TanggalSelesai");

                    b.Property<string>("TeleponPengampu")
                        .HasColumnType("text")
                        .HasColumnName("TeleponPengampu");

                    b.Property<string>("TujuanPermohonan")
                        .HasColumnType("text")
                        .HasColumnName("TujuanPermohonan");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("PermohonanPPIDID");

                    b.HasIndex("NoPermohonan")
                        .IsUnique();

                    b.HasIndex("PribadiID");

                    b.HasIndex("StatusPPIDID");

                    b.ToTable("PermohonanPPID", "public");
                });

            modelBuilder.Entity("PermintaanData.Models.PermohonanPPIDDetail", b =>
                {
                    b.Property<Guid>("PermohonanPPIDDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PermohonanPPIDDetailID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("DetailKeperluan")
                        .HasColumnType("text")
                        .HasColumnName("DetailKeperluan");

                    b.Property<int?>("KeperluanID")
                        .HasColumnType("integer")
                        .HasColumnName("KeperluanID");

                    b.Property<Guid?>("PermohonanPPIDID")
                        .HasColumnType("uuid")
                        .HasColumnName("PermohonanPPIDID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("PermohonanPPIDDetailID");

                    b.HasIndex("KeperluanID");

                    b.HasIndex("PermohonanPPIDID");

                    b.ToTable("PermohonanPPIDDetail", "public");
                });

            modelBuilder.Entity("PermintaanData.Models.Pribadi", b =>
                {
                    b.Property<Guid>("PribadiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PribadiID");

                    b.Property<string>("Alamat")
                        .HasColumnType("text")
                        .HasColumnName("Alamat");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<bool?>("IsKendaraan")
                        .HasColumnType("boolean")
                        .HasColumnName("IsKendaraan");

                    b.Property<string>("KabupatenID")
                        .HasColumnType("text")
                        .HasColumnName("KabupatenID");

                    b.Property<string>("KecamatanID")
                        .HasColumnType("text")
                        .HasColumnName("KecamatanID");

                    b.Property<bool?>("Kelamin")
                        .HasColumnType("boolean")
                        .HasColumnName("Kelamin");

                    b.Property<string>("KelurahanID")
                        .HasColumnType("text")
                        .HasColumnName("KelurahanID");

                    b.Property<string>("NIK")
                        .HasColumnType("text")
                        .HasColumnName("NIK");

                    b.Property<string>("Nama")
                        .HasColumnType("text")
                        .HasColumnName("Nama");

                    b.Property<string>("NamaKabupaten")
                        .HasColumnType("text")
                        .HasColumnName("NamaKabupaten");

                    b.Property<string>("NamaKecamatan")
                        .HasColumnType("text")
                        .HasColumnName("NamaKecamatan");

                    b.Property<string>("NamaKelurahan")
                        .HasColumnType("text")
                        .HasColumnName("NamaKelurahan");

                    b.Property<string>("RT")
                        .HasColumnType("text")
                        .HasColumnName("RT");

                    b.Property<string>("RW")
                        .HasColumnType("text")
                        .HasColumnName("RW");

                    b.Property<string>("Telepon")
                        .HasColumnType("text")
                        .HasColumnName("Telepon");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("PribadiID");

                    b.ToTable("Pribadi", "public");
                });

            modelBuilder.Entity("PermintaanData.Models.PribadiPPID", b =>
                {
                    b.Property<Guid>("PribadiPPIDID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PribadiPPIDID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Fakultas")
                        .HasColumnType("text")
                        .HasColumnName("Fakultas");

                    b.Property<string>("Jurusan")
                        .HasColumnType("text")
                        .HasColumnName("Jurusan");

                    b.Property<string>("Lembaga")
                        .HasColumnType("text")
                        .HasColumnName("Lembaga");

                    b.Property<string>("NIM")
                        .HasColumnType("text")
                        .HasColumnName("NIM");

                    b.Property<string>("NamaProvinsi")
                        .HasColumnType("text")
                        .HasColumnName("NamaProvinsi");

                    b.Property<string>("Pekerjaan")
                        .HasColumnType("text")
                        .HasColumnName("pekerjaan");

                    b.Property<Guid?>("PribadiID")
                        .HasColumnType("uuid")
                        .HasColumnName("PribadiID");

                    b.Property<string>("ProvinsiID")
                        .HasColumnType("text")
                        .HasColumnName("ProvinsiID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("PribadiPPIDID");

                    b.HasIndex("PribadiID")
                        .IsUnique();

                    b.ToTable("PribadiPPID", "public");
                });

            modelBuilder.Entity("PermintaanData.Models.StatusPPID", b =>
                {
                    b.Property<int>("StatusPPIDID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("StatusPPIDID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusPPIDID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("NamaStatusPPID")
                        .HasColumnType("text")
                        .HasColumnName("NamaStatusPPID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("StatusPPIDID");

                    b.ToTable("StatusPPID", "public");

                    b.HasData(
                        new
                        {
                            StatusPPIDID = 1,
                            NamaStatusPPID = "Baru"
                        },
                        new
                        {
                            StatusPPIDID = 2,
                            NamaStatusPPID = "Terdaftar"
                        },
                        new
                        {
                            StatusPPIDID = 3,
                            NamaStatusPPID = "Identifikasi Awal"
                        },
                        new
                        {
                            StatusPPIDID = 4,
                            NamaStatusPPID = "Menunggu Surat Izin"
                        },
                        new
                        {
                            StatusPPIDID = 5,
                            NamaStatusPPID = "Surat Izin Terbit"
                        },
                        new
                        {
                            StatusPPIDID = 6,
                            NamaStatusPPID = "Didisposisi"
                        },
                        new
                        {
                            StatusPPIDID = 7,
                            NamaStatusPPID = "Sedang Diproses"
                        },
                        new
                        {
                            StatusPPIDID = 8,
                            NamaStatusPPID = "Observasi Dijadwalkan"
                        },
                        new
                        {
                            StatusPPIDID = 9,
                            NamaStatusPPID = "Observasi Selesai"
                        },
                        new
                        {
                            StatusPPIDID = 10,
                            NamaStatusPPID = "Data Siap"
                        },
                        new
                        {
                            StatusPPIDID = 11,
                            NamaStatusPPID = "Selesai"
                        },
                        new
                        {
                            StatusPPIDID = 12,
                            NamaStatusPPID = "Wawancara Dijadwalkan"
                        },
                        new
                        {
                            StatusPPIDID = 13,
                            NamaStatusPPID = "Wawancara Selesai"
                        },
                        new
                        {
                            StatusPPIDID = 14,
                            NamaStatusPPID = "Menunggu Verifikasi Kasubkel"
                        },
                        new
                        {
                            StatusPPIDID = 15,
                            NamaStatusPPID = "Pengisian Feedback Pemohon"
                        });
                });

            modelBuilder.Entity("PermintaanData.Models.SubTaskPPID", b =>
                {
                    b.Property<Guid>("SubTaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("SubTaskID");

                    b.Property<string>("Catatan")
                        .HasColumnType("text")
                        .HasColumnName("Catatan");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("FilePath")
                        .HasColumnType("text")
                        .HasColumnName("FilePath");

                    b.Property<string>("JenisTask")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("JenisTask");

                    b.Property<string>("NamaFile")
                        .HasColumnType("text")
                        .HasColumnName("NamaFile");

                    b.Property<string>("NamaPIC")
                        .HasColumnType("text")
                        .HasColumnName("NamaPIC");

                    b.Property<string>("Operator")
                        .HasColumnType("text")
                        .HasColumnName("Operator");

                    b.Property<Guid>("PermohonanPPIDID")
                        .HasColumnType("uuid")
                        .HasColumnName("PermohonanPPIDID");

                    b.Property<DateTime?>("SelesaiAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SelesaiAt");

                    b.Property<int>("StatusTask")
                        .HasColumnType("integer")
                        .HasColumnName("StatusTask");

                    b.Property<DateOnly?>("TanggalJadwal")
                        .HasColumnType("date")
                        .HasColumnName("TanggalJadwal");

                    b.Property<string>("TeleponPIC")
                        .HasColumnType("text")
                        .HasColumnName("TeleponPIC");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<TimeOnly?>("WaktuJadwal")
                        .HasColumnType("time without time zone")
                        .HasColumnName("WaktuJadwal");

                    b.HasKey("SubTaskID");

                    b.HasIndex("PermohonanPPIDID");

                    b.HasIndex("PermohonanPPIDID", "JenisTask");

                    b.ToTable("SubTaskPPID", "public");
                });

            modelBuilder.Entity("PermintaanData.Models.AuditLogPPID", b =>
                {
                    b.HasOne("PermintaanData.Models.PermohonanPPID", "Permohonan")
                        .WithMany("AuditLog")
                        .HasForeignKey("PermohonanPPIDID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permohonan");
                });

            modelBuilder.Entity("PermintaanData.Models.DokumenPPID", b =>
                {
                    b.HasOne("PermintaanData.Models.JenisDokumenPPID", "JenisDokumen")
                        .WithMany()
                        .HasForeignKey("JenisDokumenPPIDID");

                    b.HasOne("PermintaanData.Models.PermohonanPPID", "Permohonan")
                        .WithMany("Dokumen")
                        .HasForeignKey("PermohonanPPIDID");

                    b.Navigation("JenisDokumen");

                    b.Navigation("Permohonan");
                });

            modelBuilder.Entity("PermintaanData.Models.JadwalPPID", b =>
                {
                    b.HasOne("PermintaanData.Models.PermohonanPPID", "Permohonan")
                        .WithMany("Jadwal")
                        .HasForeignKey("PermohonanPPIDID");

                    b.Navigation("Permohonan");
                });

            modelBuilder.Entity("PermintaanData.Models.PermohonanPPID", b =>
                {
                    b.HasOne("PermintaanData.Models.Pribadi", "Pribadi")
                        .WithMany("Permohonan")
                        .HasForeignKey("PribadiID");

                    b.HasOne("PermintaanData.Models.StatusPPID", "Status")
                        .WithMany()
                        .HasForeignKey("StatusPPIDID");

                    b.Navigation("Pribadi");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("PermintaanData.Models.PermohonanPPIDDetail", b =>
                {
                    b.HasOne("PermintaanData.Models.Keperluan", "Keperluan")
                        .WithMany()
                        .HasForeignKey("KeperluanID");

                    b.HasOne("PermintaanData.Models.PermohonanPPID", "Permohonan")
                        .WithMany("Detail")
                        .HasForeignKey("PermohonanPPIDID");

                    b.Navigation("Keperluan");

                    b.Navigation("Permohonan");
                });

            modelBuilder.Entity("PermintaanData.Models.PribadiPPID", b =>
                {
                    b.HasOne("PermintaanData.Models.Pribadi", "Pribadi")
                        .WithOne("PribadiPPID")
                        .HasForeignKey("PermintaanData.Models.PribadiPPID", "PribadiID");

                    b.Navigation("Pribadi");
                });

            modelBuilder.Entity("PermintaanData.Models.SubTaskPPID", b =>
                {
                    b.HasOne("PermintaanData.Models.PermohonanPPID", "Permohonan")
                        .WithMany()
                        .HasForeignKey("PermohonanPPIDID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permohonan");
                });

            modelBuilder.Entity("PermintaanData.Models.PermohonanPPID", b =>
                {
                    b.Navigation("AuditLog");

                    b.Navigation("Detail");

                    b.Navigation("Dokumen");

                    b.Navigation("Jadwal");
                });

            modelBuilder.Entity("PermintaanData.Models.Pribadi", b =>
                {
                    b.Navigation("Permohonan");

                    b.Navigation("PribadiPPID");
                });
#pragma warning restore 612, 618
        }
    }
}
